// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: protoc-gen-grpc-gateway-2/testdata/echo_service.proto

// Echo Service
//
// Echo Service API consists of a single service which returns
// a message.

package echo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
)
